# Generated by Django 5.2.13 on 2026-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fact', models.TextField(help_text='A specific fact or preference about Sawan.')),
                ('context', models.CharField(blank=True, help_text='Where or why this was learned.', max_length=255, null=True)),
            ],
        ),
    ]
