# Generated by Django 5.2.13 on 2026-05-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0002_userfact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFact',
            new_name='SawanFact',
        ),
    ]
