# Generated by Django 5.2.13 on 2026-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0003_rename_userfact_sawanfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='pollen_cost',
            field=models.FloatField(default=0.1),
        ),
    ]
