# Generated by Django 5.2.13 on 2026-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0006_radtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('evolution', 'Evolutionary Log'), ('research', 'Research Finding'), ('blueprint', 'System Blueprint'), ('milestone', 'Life Milestone')], default='research', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
