# Generated by Django 5.2.13 on 2026-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0007_radlearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='radtask',
            name='created_by',
            field=models.CharField(choices=[('sawan', 'Sawan (Creator)'), ('rad', 'Rad (Organism)')], default='rad', max_length=10),
        ),
        migrations.AddField(
            model_name='radtask',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
