# Generated by Django 5.2.13 on 2026-05-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0008_radtask_created_by_radtask_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
