# Generated by Django 5.2.13 on 2026-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0009_chatmessage_attachment_chatmessage_attachment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('fix_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
