# Generated by Django 5.2.13 on 2026-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0010_neuralerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='radtask',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radtask',
            name='recurrence_interval',
            field=models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
