# Generated by Django 5.2.13 on 2026-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0011_radtask_is_recurring_radtask_recurrence_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
