# Generated by Django 5.2.13 on 2026-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0012_chatmessage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='radlearning',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
