# Generated by Django 5.2.13 on 2026-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0013_radlearning_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='radlearning',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='True if this relates to Sawan personally.'),
        ),
        migrations.AddField(
            model_name='radlearning',
            name='subject',
            field=models.CharField(default='system', help_text='The subject of the memory (e.g., Sawan, Rad, Chrome).', max_length=100),
        ),
        migrations.AlterField(
            model_name='radlearning',
            name='category',
            field=models.CharField(choices=[('evolution', 'Evolutionary Log'), ('research', 'Research Finding'), ('blueprint', 'System Blueprint'), ('milestone', 'Life Milestone'), ('fact', 'Personal Fact')], default='research', max_length=20),
        ),
    ]
