# Generated by Django 5.2.13 on 2026-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0013_radlearning_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawanfact',
            name='attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
