# Generated by Django 5.2.13 on 2026-05-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0014_radlearning_is_personal_radlearning_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SawanFact',
        ),
    ]
